export { Nav } from './Nav'
export { Header } from './Header'
export { TheSystem } from './TheSystem'
export { TotalIntegration } from './TotalIntegration'
export { Doubt } from './Doubt'
export { Price } from './Price'
export { LawyerSite } from './LawyerSite'
export { Contact } from './Contact'
